config/routes.rb
Rails.application.routes.draw do
  
  LOCALES = /en|pt\-BR/
  
  scope "(:locale)", locale: LOCALES do
    resources :users
    resource :confirmation, only: [:show]
    resource :user_sessions, only: [:create, :new, :destroy]
  end
  
  get '/:locale' => 'users#index', locale: LOCALES
  
  root 'users#index'
  

end

app/models/user.rb
class User < ActiveRecord::Base
    
  EMAIL_REGEXP = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
  
  validates_presence_of :email, :full_name
  validates_uniqueness_of :email
  #validates_length_of :password, minimum: 8
  #validates_length_of :password_confirmation, minimum: 8
  validates_format_of :email, with: EMAIL_REGEXP
  
  has_secure_password
  
  before_create do |user|
    user.confirmation_token = SecureRandom.urlsafe_base64
  end
  
  def confirm!
    return if confirmed?
    
    self.confirmed_at = Time.current
    self.confirmation_token = ''
    save!
  end
    
  def confirmed?
    confirmed_at.present?
  end
  
  scope :confirmed, -> { where.not(confirmed_at: nil)}
    
  def self.authenticate(email, password)
    #user = 
    confirmed.
      find_by(email: email).
      try(:authenticate, password)
  end
  
  #has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "120x90>" }
  
  #validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
    
end

app/models/user_session.rb
class UserSession
    include ActiveModel::Model
    
    attr_accessor :email, :password
    validates_presence_of :email, :password
    
    def initialize(session, attributes={})
        @session = session
        @email = attributes[:email]
        @password = attributes[:password]
    end
    
    def authenticate!
        user = User.authenticate(@email, @password)
        
        if user.present?
            store(user)
        else
            errors.add(:base, :invalid_login)
            false
        end
    end
    
    def store(user)
        @session[:user_id] = user.id
    end
    
    def current_user
        User.find(@session[:user_id])
    end
    
    def user_signed_in?
        @session[:user_id].present?
    end
    
    def destroy
        @session[:user_id] = nil
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  delegate :current_user, :user_signed_in?, to: :user_session
  
  helper_method :current_user, :user_signed_in?
  
  protect_from_forgery with: :exception
  
  before_action do
    I18n.locale = params[:locale] || I18n.default_locale
  end
  
  def default_url_options
    { locale: I18n.locale }
  end
  
  def user_session
    UserSession.new(session)    
  end
  
  def require_authentication
    unless user_signed_in?
      redirect_to new_user_sessions_path,
        alert: t('flash.alert.needs_login')
    end
  end
  
  def require_no_authentication
    if user_signed_in?
      redirect_to root_path,
        notice: t('flash.notice.already_logged_in')
    end
  end
  
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController
  def show
    user = User.find_by(confirmation_token: params[:token])
    
    if user.present?
      user.confirm!
      redirect_to user, notice: I18n.t('confirmations.success')
    else
      redirect_to root_path
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
    
    before_action :require_no_authentication, only: [:new, :create]
    before_action :require_authentication, only: :destroy
    
    def new
        @user_session = UserSession.new(session)
    end
    
    def create
        @user_session = UserSession.new(session, params[:user_session])
        if @user_session.authenticate!
            redirect_to root_path, notice: t('flash.notice.signed_in')
        else
            render :new
        end
    end
    
    def destroy
        user_session.destroy
        redirect_to root_path, notice: t('flash.notice.signed_out')
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	before_action :require_no_authentication, only: [:new, :create]
  before_action :can_change, only: [:edit, :update]
	
	def show
		@user = User.find(params[:id])
	end
		
	def new
   @user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			SignupMailer.confirm_email(@user).deliver
			redirect_to @user, 
									notice: "Sucesso"
		else
			render :new
		end
	end
	
	def edit
		@user = User.find(params[:id])
	end
	
	def update
	  @user = User.find(params[:id])
	  if @user.update(user_params)
	    redirect_to @user,
	     						notice: 'Cadastro atualizado com sucesso!'
	  else
	    render action: :edit
	  end
	end
	
	private
	
	def user_params
		params.
				require(:user).
				permit(:email, :full_name, :password, :password_confirmation, :avatar, :address_line1,
					 		 :address_line2, :number, :zipcode, :city, :state, :cellphone)
	end
	
	def can_change
	  unless user_signed_in? && current_user == user
      redirect_to user_path(params[:id])
	  end
	end
    
  def user
  	@user ||= User.find(params[:id])
  end
		
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_tag(model, attribute)
    if model.errors.has_key? attribute
      content_tag(
        :div, model.errors[attribute].first,
        class: 'error_message'
        )
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_user_navbar.html.erb
<nav>
  <ul>
    <li>
        <%= link_to t('layout.my_profile'), user_path(current_user) %> 
    </li>
    <li>
        <%= link_to t('layout.signout'), user_sessions_path, method: :delete %> 
    </li>
  </ul>
</nav>

app/views/layouts/_visitor_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to t('layout.signup'), new_user_path %> </li>
    <li><%= link_to t('layout.signin'), new_user_sessions_path %> </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstOnCloud9</title>
  <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand" href="/alura">Minha Loja</a>
			</div>
			<div>
				<ul class="nav navbar-nav">
					<li><a href="produto-formulario.php">Adicionar Produto</a></li>
					<li><a href="produto-lista.php">Produtos</a></li>
					<li><a href="contato.php">Contato</a></li>
				</ul>
			</div>
			
			<div id="header-wrap">
	      <% if user_signed_in? %>
	        <%= render 'layouts/user_navbar' %>
	      <% else %>
	        <%= render 'layouts/visitor_navbar' %>
	      <% end %>
		  </div>
			
		</div>
	</div>
	
	<div class="container">
		<div class="principal">

      <%= yield %>
      
    </div>
  </div>

</body>
</html>

app/views/user_sessions/new.html.erb
<h1><%= t '.title' %> </h1>

<% if @user_session.errors.has_key? :base %>
    <div id="error_explanation">
        <%= @user_session.errors[:base].join(', ') %>
    </div>
<% end %>

<%= form_for @user_session do |f| %>
    <p>
        <%= f.label :email %>
        <%= f.text_field :email %>
        <%= error_tag @user_session, :email %>
    </p>
    <p>
        <%= f.label :password %>
        <%= f.password_field :password %>
        <%= error_tag @user_session, :password %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

<p><%= link_to t('.sign_up'), new_user_path %> </p>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <%= t 'general.form_error' %>
    </div>
<% end %>

<p id="notice"><%= notice %> </p>

<%= form_for @user do |f| %>

<!-- , :url => users_path, :html => { :multipart => true } do |f| % -->

    <!-- <div class="field">
        %= #f.label :avatar %><br />
        %= #f.file_field :avatar %>
        %= #error_tag @user, :avatar %>
    </div> -->
    
    <p >
        <%= f.label :full_name %>
        <%= f.text_field :full_name, class:"form-control" %>
        <%= error_tag @user, :full_name %>
    </p>
    <p>
        <%= f.label :email %>
        <%= f.text_field :email, class:"form-control" %>
        <%= error_tag @user, :email %>
    </p>
    <p>
        <%= f.label :password %>
        <%= f.password_field :password, class:"form-control" %>
        <%= error_tag @user, :password %>
    </p>
    <p>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class:"form-control" %>
        <%= error_tag @user, :password_confirmation %>
    </p>
    
    <h2>Dados Adicionais</h2>
    
    <p >
        <%= f.label :address_line1 %>
        <%= f.text_field :address_line1, class:"form-control" %>
    </p>
    <p >
        <%= f.label :address_line2 %>
        <%= f.text_field :address_line2, class:"form-control" %>
    </p>
    <p >
        <%= f.label :number %>
        <%= f.text_field :number, class:"form-control" %>
    </p>
    <p >
        <%= f.label :zipcode %>
        <%= f.text_field :zipcode, class:"form-control" %>
    </p>
    <p >
        <%= f.label :city %>
        <%= f.text_field :city, class:"form-control" %>
    </p>
    <p >
        <%= f.label :state %>
        <%= f.text_field :state, class:"form-control" %>
    </p>
    <p >
        <%= f.label :cellphone %>
        <%= f.text_field :cellphone, class:"form-control" %>
    </p>
    
    <p>
        <%= f.submit %>
    </p>
    

<% end %>

app/views/users/edit.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Pronto!</h1>

app/views/users/new.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %> </p>

<h2><%= t '.profile' , user_name: @user.full_name %></h2>
<%= image_tag @user.avatar.url(:medium) %>

<%= link_to t("links.edit"), edit_user_path(@user) %>